# Form implementation generated from reading ui file './ui/train_page.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(963, 773)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 30)
        self.verticalLayout.setSpacing(11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(parent=self.widget_2)
        self.frame.setMinimumSize(QtCore.QSize(800, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_5 = QtWidgets.QWidget(parent=self.frame)
        self.widget_5.setStyleSheet("background-color: rgb(68, 68, 68);\n"
"border-radius:20px;")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_2 = QtWidgets.QFrame(parent=self.widget_5)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.comboBox_3 = QtWidgets.QComboBox(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"    border: 2px solid #555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    color: #fff;\n"
"    border-radius: 0px; /* Set border radius to 0px */\n"
"}\n"
"")
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_3.addWidget(self.comboBox_3)
        self.verticalLayout_8.addWidget(self.frame_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_5)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_11 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_14 = QtWidgets.QWidget(parent=self.widget_11)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_15 = QtWidgets.QLabel(parent=self.widget_14)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_11.addWidget(self.label_15)
        self.input_model_type = QtWidgets.QLineEdit(parent=self.widget_14)
        self.input_model_type.setMinimumSize(QtCore.QSize(0, 30))
        self.input_model_type.setStyleSheet("QLineEdit {\n"
"                background-color: #333;\n"
"                color: #fff;\n"
"                border: 2px solid #555;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"            }")
        self.input_model_type.setObjectName("input_model_type")
        self.verticalLayout_11.addWidget(self.input_model_type)
        self.horizontalLayout_7.addWidget(self.widget_14)
        self.widget_13 = QtWidgets.QWidget(parent=self.widget_11)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_7.addWidget(self.widget_13)
        self.verticalLayout_9.addWidget(self.widget_11)
        self.label_9 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.textEdit = QtWidgets.QTextEdit(parent=self.widget_3)
        self.textEdit.setStyleSheet("QTextEdit {\n"
"            background-color: #f0f0f0;\n"
"            border: 2px solid #ccc;\n"
"            border-radius: 5px;\n"
"            font-family: Arial, sans-serif;\n"
"            font-size: 14px;\n"
"            padding: 10px;\n"
"        }\n"
"        \n"
"        QTextEdit::hover {\n"
"            background-color: #e0e0e0;\n"
"        }\n"
"        \n"
"        QTextEdit::focus {\n"
"            border-color: #4CAF50;\n"
"        }")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_9.addWidget(self.textEdit)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.widget_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 352, 456))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_12 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget_12.setStyleSheet("background-color: rgb(113, 113, 113);")
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_7.setContentsMargins(4, 9, 4, 9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_3 = QtWidgets.QFrame(parent=self.widget_12)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 180))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.comboBox_4 = QtWidgets.QComboBox(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setStyleSheet("QComboBox {\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"    border: 2px solid #555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    color: #fff;\n"
"    border-radius: 0px; /* Set border radius to 0px */\n"
"}\n"
"")
        self.comboBox_4.setObjectName("comboBox_4")
        self.verticalLayout_6.addWidget(self.comboBox_4)
        self.datasetname_input = QtWidgets.QLineEdit(parent=self.frame_3)
        self.datasetname_input.setMinimumSize(QtCore.QSize(0, 30))
        self.datasetname_input.setStyleSheet("QLineEdit {\n"
"                background-color: #333;\n"
"                color: #fff;\n"
"                border: 2px solid #555;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"            }")
        self.datasetname_input.setObjectName("datasetname_input")
        self.verticalLayout_6.addWidget(self.datasetname_input)
        self.opmodetg = QtWidgets.QCheckBox(parent=self.frame_3)
        self.opmodetg.setStyleSheet("color:rgb(255, 255, 255)")
        self.opmodetg.setObjectName("opmodetg")
        self.verticalLayout_6.addWidget(self.opmodetg)
        self.genDataset_info = QtWidgets.QLabel(parent=self.frame_3)
        self.genDataset_info.setObjectName("genDataset_info")
        self.verticalLayout_6.addWidget(self.genDataset_info)
        self.genDataset_button = QtWidgets.QPushButton(parent=self.frame_3)
        self.genDataset_button.setMinimumSize(QtCore.QSize(0, 30))
        self.genDataset_button.setStyleSheet("QPushButton {\n"
"                background-color: #007bff;\n"
"                color: #fff;\n"
"                border: 2px solid #007bff;\n"
"                border-radius: 5px;\n"
"                padding: 7px 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #0056b3;\n"
"                border: 2px solid #0056b3;\n"
"            }")
        self.genDataset_button.setObjectName("genDataset_button")
        self.verticalLayout_6.addWidget(self.genDataset_button)
        self.widget_8 = QtWidgets.QWidget(parent=self.frame_3)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_6.addWidget(self.widget_8)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.verticalLayout_4.addWidget(self.widget_12)
        self.widget_15 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget_15.setStyleSheet("background-color: rgb(113, 113, 113);")
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_12.setContentsMargins(4, 9, 4, 9)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_4 = QtWidgets.QFrame(parent=self.widget_15)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 180))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_13.addWidget(self.label_4)
        self.comboBox_5 = QtWidgets.QComboBox(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        self.comboBox_5.setStyleSheet("QComboBox {\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"    border: 2px solid #555;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    color: #fff;\n"
"    border-radius: 0px; /* Set border radius to 0px */\n"
"}\n"
"")
        self.comboBox_5.setObjectName("comboBox_5")
        self.verticalLayout_13.addWidget(self.comboBox_5)
        self.trainmodelName = QtWidgets.QLineEdit(parent=self.frame_4)
        self.trainmodelName.setMinimumSize(QtCore.QSize(0, 30))
        self.trainmodelName.setStyleSheet("QLineEdit {\n"
"                background-color: #333;\n"
"                color: #fff;\n"
"                border: 2px solid #555;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"            }")
        self.trainmodelName.setObjectName("trainmodelName")
        self.verticalLayout_13.addWidget(self.trainmodelName)
        self.widget_16 = QtWidgets.QWidget(parent=self.frame_4)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_17 = QtWidgets.QWidget(parent=self.widget_16)
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_12 = QtWidgets.QLabel(parent=self.widget_17)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_14.addWidget(self.label_12)
        self.input_epoch = QtWidgets.QLineEdit(parent=self.widget_17)
        self.input_epoch.setMinimumSize(QtCore.QSize(0, 30))
        self.input_epoch.setStyleSheet("QLineEdit {\n"
"                background-color: #333;\n"
"                color: #fff;\n"
"                border: 2px solid #555;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"            }")
        self.input_epoch.setObjectName("input_epoch")
        self.verticalLayout_14.addWidget(self.input_epoch)
        self.horizontalLayout_8.addWidget(self.widget_17)
        self.widget_18 = QtWidgets.QWidget(parent=self.widget_16)
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_13 = QtWidgets.QLabel(parent=self.widget_18)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_15.addWidget(self.label_13)
        self.input_split = QtWidgets.QLineEdit(parent=self.widget_18)
        self.input_split.setMinimumSize(QtCore.QSize(0, 30))
        self.input_split.setStyleSheet("QLineEdit {\n"
"                background-color: #333;\n"
"                color: #fff;\n"
"                border: 2px solid #555;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"            }")
        self.input_split.setObjectName("input_split")
        self.verticalLayout_15.addWidget(self.input_split)
        self.horizontalLayout_8.addWidget(self.widget_18)
        self.verticalLayout_13.addWidget(self.widget_16)
        self.verticalLayout_12.addWidget(self.frame_4)
        self.save_button = QtWidgets.QPushButton(parent=self.widget_15)
        self.save_button.setMinimumSize(QtCore.QSize(0, 30))
        self.save_button.setStyleSheet("QPushButton {\n"
"                background-color: #007bff;\n"
"                color: #fff;\n"
"                border: 2px solid #007bff;\n"
"                border-radius: 5px;\n"
"                padding: 7px 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #0056b3;\n"
"                border: 2px solid #0056b3;\n"
"            }")
        self.save_button.setObjectName("save_button")
        self.verticalLayout_12.addWidget(self.save_button)
        self.verticalLayout_4.addWidget(self.widget_15)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_9.addWidget(self.scrollArea)
        self.verticalLayout_8.addWidget(self.widget_3, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.widget_4 = QtWidgets.QWidget(parent=self.frame)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.widget_4)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_2)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 20)
        self.horizontalLayout_4.setSpacing(9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.back_button = QtWidgets.QPushButton(parent=self.widget_6)
        self.back_button.setMinimumSize(QtCore.QSize(150, 30))
        self.back_button.setMaximumSize(QtCore.QSize(150, 16777215))
        self.back_button.setStyleSheet("QPushButton {\n"
"                background-color: #007bff;\n"
"                color: #fff;\n"
"                border: 2px solid #007bff;\n"
"                border-radius: 5px;\n"
"                padding: 7px 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #0056b3;\n"
"                border: 2px solid #0056b3;\n"
"            }")
        self.back_button.setObjectName("back_button")
        self.horizontalLayout_4.addWidget(self.back_button)
        self.verticalLayout.addWidget(self.widget_6, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\"># MODEL CLASSES</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">MODEL NAME</span></p></body></html>"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">MODEL TYPE</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">DESCRIPTION</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">DATASET NAME</span></p></body></html>"))
        self.opmodetg.setText(_translate("Form", "APPEND"))
        self.genDataset_info.setText(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.genDataset_button.setText(_translate("Form", "GENERATE DATASET"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">TRAIN MODEL NAME</span></p></body></html>"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">EPOCHS</span></p></body></html>"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">SPLIT RATE</span></p></body></html>"))
        self.save_button.setText(_translate("Form", "TRAIN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
        self.back_button.setText(_translate("Form", "SAVE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
